---
filebeat_version: 7.x
filebeat_create_config: true

filebeat_inputs:
  - type: log
    paths:
      - "/var/log/*.log"

filebeat_output_logstash_hosts:
  - "logstash:5044"

filebeat_enable_logging: false
filebeat_log_level: warning
filebeat_log_dir: /var/log/mybeat
filebeat_log_filename: mybeat.log

filebeat_ssl_dir: /etc/pki/logstash
filebeat_ssl_certificate_file: "/root/ansible/Softserve_DevOps_Demo_1/roles/filebeats/filebeat.crt"
filebeat_ssl_key_file: "/root/ansible/Softserve_DevOps_Demo_1/roles/filebeats/filebeat.key"
filebeat_ssl_insecure: "true"
