---
filebeat_version: 7.x
filebeat_create_config: true

filebeat_output_logstash_hosts: ip-address-here

filebeat_enable_logging: true
filebeat_log_level: warning
filebeat_log_dir: /var/log/mybeat
filebeat_log_filename: mybeat.log

